
CREATE DATABASE ehrs_db;

CREATE TABLE users (
    id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE,
    password VARCHAR(255),
    email VARCHAR(100) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



CREATE TABLE employeehealthrecord (
    UniqueNumber INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EmployeeNo VARCHAR(255) NOT NULL COLLATE utf8mb4_general_ci,
    EmployeeName VARCHAR(255) COLLATE utf8mb4_general_ci,
    DateOfBirth DATE,
    Sex ENUM('male', 'female') COLLATE utf8mb4_general_ci,
    IdentificationMark VARCHAR(255) COLLATE utf8mb4_general_ci,
    FathersName VARCHAR(255) COLLATE utf8mb4_general_ci,
    MaritalStatus ENUM('Married', 'Unmarried') COLLATE utf8mb4_general_ci,
    HusbandsName VARCHAR(255) COLLATE utf8mb4_general_ci,
    Address TEXT COLLATE utf8mb4_general_ci,
    Dependent VARCHAR(255) COLLATE utf8mb4_general_ci,
    Mobile VARCHAR(20) COLLATE utf8mb4_general_ci,
    JoiningDate DATE,
    DateOfExamination DATE,
    Company VARCHAR(255) COLLATE utf8mb4_general_ci,
    Department VARCHAR(255) COLLATE utf8mb4_general_ci,
    Designation VARCHAR(255) COLLATE utf8mb4_general_ci,
    H_OHabit TEXT COLLATE utf8mb4_general_ci,
    Prev_Occ_History TEXT COLLATE utf8mb4_general_ci,
    Temperature FLOAT,
    Height FLOAT,
    ChestBeforeBreathing FLOAT,
    Pulse INT(11),
    Weight FLOAT,
    ChestAfterBreathing FLOAT,
    BP VARCHAR(20) COLLATE utf8mb4_general_ci,
    BMI FLOAT,
    SpO2 FLOAT,
    RespirationRate INT(11),
    RightEyeSpecs VARCHAR(255) COLLATE utf8mb4_general_ci,
    LeftEyeSpecs VARCHAR(255) COLLATE utf8mb4_general_ci,
    NearVisionRight VARCHAR(255) COLLATE utf8mb4_general_ci,
    NearVisionLeft VARCHAR(255) COLLATE utf8mb4_general_ci,
    DistantVisionRight VARCHAR(255) COLLATE utf8mb4_general_ci,
    DistantVisionLeft VARCHAR(255) COLLATE utf8mb4_general_ci,
    ColourVision VARCHAR(255) COLLATE utf8mb4_general_ci,
    Eye VARCHAR(255) COLLATE utf8mb4_general_ci,
    Nose VARCHAR(255) COLLATE utf8mb4_general_ci,
    Conjunctiva VARCHAR(255) COLLATE utf8mb4_general_ci,
    Ear VARCHAR(255) COLLATE utf8mb4_general_ci,
    Tongue VARCHAR(255) COLLATE utf8mb4_general_ci,
    Nails VARCHAR(255) COLLATE utf8mb4_general_ci,
    Throat VARCHAR(255) COLLATE utf8mb4_general_ci,
    Skin VARCHAR(255) COLLATE utf8mb4_general_ci,
    Teeth VARCHAR(255) COLLATE utf8mb4_general_ci,
    PEFR VARCHAR(255) COLLATE utf8mb4_general_ci,
    Eczema TINYINT(1),
    Cyanosis TINYINT(1),
    Jaundice TINYINT(1),
    Anaemia TINYINT(1),
    Oedema TINYINT(1),
    Clubbing TINYINT(1),
    Allergy TINYINT(1),
    Lymphnode VARCHAR(255) COLLATE utf8mb4_general_ci,
    KnownHypertension TINYINT(1),
    Diabetes TINYINT(1),
    Dyslipidemia TINYINT(1),
    RadiationEffect TINYINT(1),
    Vertigo TINYINT(1),
    Tuberculosis TINYINT(1),
    ThyroidDisorder TINYINT(1),
    Epilepsy TINYINT(1),
    Br_Asthma TINYINT(1),
    HeartDisease TINYINT(1),
    PresentComplaint TEXT COLLATE utf8mb4_general_ci,
    Father VARCHAR(255) COLLATE utf8mb4_general_ci,
    Mother VARCHAR(255) COLLATE utf8mb4_general_ci,
    Brother VARCHAR(255) COLLATE utf8mb4_general_ci,
    Sister VARCHAR(255) COLLATE utf8mb4_general_ci,
    RespirationSystem VARCHAR(255) COLLATE utf8mb4_general_ci,
    GenitoUrinary VARCHAR(255) COLLATE utf8mb4_general_ci,
    CVS VARCHAR(255) COLLATE utf8mb4_general_ci,
    CNS VARCHAR(255) COLLATE utf8mb4_general_ci,
    PerAbdomen VARCHAR(255) COLLATE utf8mb4_general_ci,
    ENT VARCHAR(255) COLLATE utf8mb4_general_ci,
    PFT VARCHAR(255) COLLATE utf8mb4_general_ci,
    XRayChest VARCHAR(255) COLLATE utf8mb4_general_ci,
    VertigoTest VARCHAR(255) COLLATE utf8mb4_general_ci,
    Audiometry VARCHAR(255) COLLATE utf8mb4_general_ci,
    ECG VARCHAR(255) COLLATE utf8mb4_general_ci,
    HB FLOAT,
    TC INT(11),
    DC VARCHAR(255) COLLATE utf8mb4_general_ci,
    RBC FLOAT,
    Platelet INT(11),
    ESR INT(11),
    FBS FLOAT,
    PP2BS FLOAT,
    SGPT FLOAT,
    SCreatintine FLOAT,
    RBS FLOAT,
    SChol FLOAT,
    STRG FLOAT,
    SHDL FLOAT,
    SLDL FLOAT,
    CHRatio FLOAT,
    UrineColour VARCHAR(255) COLLATE utf8mb4_general_ci,
    UrineReaction VARCHAR(255) COLLATE utf8mb4_general_ci,
    UrineAlbumin VARCHAR(255) COLLATE utf8mb4_general_ci,
    UrineSugar VARCHAR(255) COLLATE utf8mb4_general_ci,
    UrinePusCell VARCHAR(255) COLLATE utf8mb4_general_ci,
    UrineRBC VARCHAR(255) COLLATE utf8mb4_general_ci,
    UrineEpiCell VARCHAR(255) COLLATE utf8mb4_general_ci,
    UrineCrystal VARCHAR(255) COLLATE utf8mb4_general_ci,
    HealthStatus VARCHAR(255) COLLATE utf8mb4_general_ci,
    NameOfDoctor VARCHAR(255) COLLATE utf8mb4_general_ci,
    DoctorSignature VARCHAR(255) COLLATE utf8mb4_general_ci,
    JobRestriction TEXT COLLATE utf8mb4_general_ci,
    ReviewedBy VARCHAR(255) COLLATE utf8mb4_general_ci);